# Generated by Django 3.0.7 on 2020-06-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_label', models.CharField(max_length=120, verbose_name="Button's label")),
                ('button_url', models.CharField(max_length=120, verbose_name="Button's link")),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtitle', models.CharField(max_length=120, verbose_name='Subtitle')),
                ('body', models.CharField(max_length=30000, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Biography',
            },
        ),
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_label', models.CharField(max_length=120, verbose_name="Button's label")),
                ('button_url', models.CharField(max_length=120, verbose_name="Button's link")),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(choices=[('TOP_CENTER', 'At the top center'), ('TOP_LEFT', 'At the top left'), ('TOP_RIGHT', 'At the top right'), ('BOTTOM_CENTER', 'At the bottom center'), ('BOTTOM_LEFT', 'At the bottom left'), ('BOTTOM_RIGHT', 'At the bottom right'), ('CENTER', 'Centered'), ('CENTER_LEFT', 'Centered left'), ('CENTER_RIGHT', 'Centered right')], default='CENTER', max_length=13, verbose_name='Text position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Carrousel item',
            },
        ),
    ]
