# Generated by Django 3.0.7 on 2020-06-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_biography_carrousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_label', models.CharField(max_length=120, verbose_name="Button's label")),
                ('button_url', models.CharField(max_length=120, verbose_name="Button's link")),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtitle', models.CharField(max_length=120, verbose_name='Subtitle')),
                ('body', models.CharField(max_length=30000, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Publication',
            },
        ),
        migrations.RenameModel(
            old_name='Carrousel',
            new_name='CarrouselItem',
        ),
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
