# Generated by Django 3.0.7 on 2020-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_create_default_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='wpp',
            new_name='contact_info',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='email',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='contact_method',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'Whatsapp')], default='EMAIL', max_length=300, verbose_name='Contact method'),
        ),
    ]
